# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Devito Codes

title: Devito Codes

description: "Devito is a Python package to implement optimized stencil computation (e.g., finite differences, image processing, machine learning) from high-level symbolic problem definitions. Devito builds on SymPy and employs automated code generation and just-in-time compilation to execute optimized computational kernels on several computer platforms, including CPUs, GPUs, and clusters thereof."

tags:
  - Devito
  - DSL
  - Domain specific language
  - HPC
  - finite-difference
  - CUDA
  - HIP
  - OpenMP
  - MPI

email: gerard@devitocodes.com

formspree_form_id: gerard@devitocodes.com

show_hero: true

# paginate: 24

twitter_username: devitocodes
linkedin_username: company/devitocodes

menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Features
    url: /features
  - title: Contact
    url: /contact

baseurl: ""

url: "https://www.devitocodes.com"


language: "en"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: "/:title"
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
# use_logo: false

theme: jekflix

# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true

#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

google_analytics: "G-39F3JRV5HY"
